name: Build MEMZ GDI Prank

on:
  push:
    paths:
      - 'memz.c'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        version: 12.2.0
        platform: x86_64

    - name: Build memz.exe
      run: gcc memz.c -o memz.exe -lgdi32 -mwindows

    - name: Upload memz.exe
      uses: actions/upload-artifact@v4
      with:
        name: memz-exe
        path: memz.exe
